### ISSUE TITLE
Cover values - specify

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Code#1]
It'd be good to add a field in the header data, whether the cover values of the respective plot were taken using percentage cover\braun blanquet\pa or other. I don't have this info (in a workable format) for sPlot 2. Should we ask Stephan?

**Comment by lenjon** [comment]
What about adding also the code that Tarek Hattab and I wrote for the resampling algortithm? I can send you the original scripts Francesco so that you can incorporate it here as open access? The scripts Tarek wrote for the resampling of sPlot are actually available via Tarek's GitHub account: https://github.com/TarekHattab/sPlot

**Comment by fmsabatini** [comment]
I integrated the original abundance\cover values, and specified the scale that was used for each species in each plot in the DT table
